{% set name = "tyro" %}
{% set version = "1.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tyro-{{ version }}.tar.gz
  sha256: 731a90c9836b77fffe7c3fa0477ef2d3b6fa91252ddc0bb4d32dadd4fcc143d4

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install --no-deps . -vv --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - typeguard >=4.0.0
    - docstring_parser >=0.15
    - typing-extensions >=4.13.0
    - eval-type-backport >=0.1.3  # [py<310]
  run_constrained:
    - PyYAML >=6.0
    - pytest >=7.1.2
    - pytest-cov >=3.0.0
    - pytest-xdist >=3.5.0
    - omegaconf >=2.2.2
    - attrs >=21.4.0
    - pyright >=1.1.349,!=1.1.379
    - mypy >=1.4.1
    - pydantic >=2.5.2,!=2.10.0
    - coverage[toml] >=6.5.0
    - eval_type_backport >=0.1.3
    - ml_collections >=0.1.0
    - msgspec >=0.18.6
    - shtab >=1.5.6
    - universal-pathlib >=0.2.0

test:
  imports:
    - tyro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brentyi/tyro
  summary: Strongly typed, zero-effort CLI interfaces
  description: |
    tyro.cli() generates command-line interfaces and config parsers from
    type-annotated Python functions and objects (dataclasses, pydantic, etc.).
  dev_url: https://github.com/brentyi/tyro
  doc_url: https://brentyi.github.io/tyro/
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
